#!/usr/bin/env bash

# Set up aliases for the common commands
alias php="docker run --rm --interactive --tty \
  --volume \$PWD:/app \
  -w=/app \
  --user $(id -u):$(id -g) \
  php:cli-alpine"
alias php74="docker run --rm --interactive --tty \
  --volume \$PWD:/app \
  -w=/app \
  --user $(id -u):$(id -g) \
  php:7.4-cli-alpine"
alias cmpr="docker run --rm --interactive --tty \
  --volume \$PWD:/app \
  -w=/app \
  --volume $SSH_AUTH_SOCK:/ssh-auth.sock \
  --volume /etc/passwd:/etc/passwd:ro \
  --volume /etc/group:/etc/group:ro \
  --env SSH_AUTH_SOCK=/ssh-auth.sock \
  --user $(id -u):$(id -g) \
  composer"
